modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory
license="GPL-3.0"

[[mods]] #mandatory
modId="ecu" #mandatory
version="${file.jarVersion}" #mandatory
displayName="ecu" #mandatory
description="Client-side only patch that allows you to unlock ALL cosmetics (+ emotes) in the Essential mod. Works on every version of Essential MC (1.8.9 - 1.20)."

[[dependencies.ecu]] #optional
modId="forge" #mandatory
mandatory=true #mandatory
versionRange="[36,)" #mandatory

[[dependencies.ecu]]
modId="minecraft"
mandatory=true
versionRange="[1.16,)"